services:
  ros_rpi:
    image: ilya9kkk/ros_arm:nn
    container_name: ros_rpi
    privileged: true
    stdin_open: true         # Открывает stdin
    tty: true                # Включает псевдотерминал
    network_mode: "host"
    ipc: "host"
    devices:
      - /dev/video0:/dev/video0
    group_add:
      - ${VIDEO_GID}
    environment:
      - DISPLAY
      - QT_X11_NO_MITSHM=1
      - XAUTHORITY
      - LD_LIBRARY_PATH=/opt/vc/lib
    volumes:
      - /opt/vc:/opt/vc
      - /dev:/dev
      - "/tmp/.X11-unix:/tmp/.X11-unix:rw"
      - ${ROOT_DIR}/workspace:/workspace
    entrypoint: ["/bin/bash", "-c", "/workspace/CONTAINER_START.bash"]

  nn1:
    image: ilya9kkk/nn_arm:latest
    container_name: nn1
    network_mode: "host"  # Используем сеть хоста
    ipc: "host"
    stdin_open: true         # Открывает stdin
    tty: true                # Включает псевдотерминал
    volumes:
      - ${ROOT_DIR}/nn_ws:/nn_ws
    # entrypoint: ["/bin/bash", "-c", "python3 /nn_ws/yolo.py; tail -f /dev/null"]
    entrypoint: ["/bin/bash", "-c", "python3 -c 'import cv2; exit(0) if \"GStreamer: YES\" in cv2.getBuildInformation() else exit(1)'"]


